[tool.poetry]
name = "rl-gym"
version = "0.1.0"
description = ""
authors = ["Valentin Canete <valentin.canete@gmail.com>"]
readme = "README.md"
packages = [{include = "rl_gym"}]

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^1.23.5"
box2d-py = "2.3.5"
torch = {url = "https://download.pytorch.org/whl/cu117/torch-1.13.0%2Bcu117-cp310-cp310-linux_x86_64.whl"}
gymnasium = {extras = ["all"], version = "^0.27.0"}

[tool.poetry.dev-dependencies]
ipykernel = "^6.17.1"
ipywidgets = "^8.0.2"
tensorboard = "^2.11.0"
yapf = "^0.32.0"
toml = "^0.10.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
