[tool.poetry]
name = "rlgym"
version = "0.1.0"
description = "Deep Renforcement Learning project made with Pytorch and Gym."
authors = ["Valentin Canete <valentin.canete@gmail.com>"]
license = "GPLv3"

[tool.poetry.dependencies]
python = "^3.10"
gym = "^0.26.2"
numpy = "^1.23.3"
matplotlib = "^3.6.0"
tqdm = "^4.64.1"
ipykernel = "^6.16.0"
ipywidgets = "^8.0.2"
torch = "^1.12.1"

[tool.poetry.dev-dependencies]
yapf = "^0.32.0"
toml = "^0.10.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
