[tool.black]
line-length = 120

[tool.ruff]
exclude = ["flax_*.py"]
ignore = ["ANN", "D", "DTZ", "T20", "B", "PLR", "INP", "FBT", "RET"]
line-length = 120
select = ["ALL"]

[tool.ruff.mccabe]
max-complexity = 12
