[tool.poetry]
name = "rl_gym"
version = "0.1.0"
description = ""
authors = ["Valentin Canete <valentin.canete@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
torch = "1.12.*"
Gymnasium = {extras = ["all"], version = "^0.26.3"}

[tool.poetry.dev-dependencies]
ipykernel = "^6.17.1"
ipywidgets = "^8.0.2"
tensorboard = "^2.11.0"
yapf = "^0.32.0"
toml = "^0.10.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
