[tool.black]
line-length = 120

[tool.ruff]
line-length = 120
select = [
  "E",
  "F",
  "W",
  "UP",
  "C4",
  "C90",
  "SIM",
  "TCH",
  "I",
  "N",
  "S",
  "A",
  "COM",
  "ICN",
  "PIE",
  "Q",
  "ARG",
  "NPY"
]

[tool.ruff.mccabe]
max-complexity = 12
